### ISSUE TITLE
Bootstrap issue

### ISSUE THREAD

**Issue by Kingrune123** [samuel-barker/Devshire#1]
trying to create two boxes of equal width beneath image with a gap in-between

**Comment by martyni8** [comment]
@samishere @dannyroach @mugslyf can you look at this pls

**Comment by samuel-barker** [comment]
@martyni8 Sure I will create a new branch and merge in 5 mins

**Comment by samuel-barker** [comment]
@Kingrune123 Did you mean this [line ](https://github.com/samuel-barker/Devshire/blob/master/index.html#L32)

**Comment by samuel-barker** [comment]
This should all be fixed now
